ALTER TABLE "StoreSettings"
ADD COLUMN "linkYoutube" TEXT,
ADD COLUMN "linkTwitter" TEXT,
ADD COLUMN "instagramAtivo" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "facebookAtivo" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "tiktokAtivo" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "youtubeAtivo" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "twitterAtivo" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "shopeeAtivo" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "linkMercadoLivre" TEXT,
ADD COLUMN "mercadoLivreAtivo" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "linkTiktokShop" TEXT,
ADD COLUMN "tiktokShopAtivo" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "linkShein" TEXT,
ADD COLUMN "sheinAtivo" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "emailSuporteAtivo" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "telefoneSuporteAtivo" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "whatsappAtivo" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "whatsappMensagem" TEXT NOT NULL DEFAULT 'Olá! Preciso de ajuda com a minha compra.',
ADD COLUMN "horariosAtendimento" JSONB,
ADD COLUMN "footerColumns" JSONB,
ADD COLUMN "footerSeloSeguranca" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "footerCopyrightTexto" TEXT NOT NULL DEFAULT 'Todos os direitos reservados.',
ADD COLUMN "footerCopyrightAno" TEXT NOT NULL DEFAULT 'automatico',
ADD COLUMN "footerCopyrightAnoFixo" INTEGER,
ADD COLUMN "razaoSocial" TEXT,
ADD COLUMN "cnpjLoja" TEXT,
ADD COLUMN "enderecoEmpresa" TEXT,
ADD COLUMN "mensagemBoasVindasAtiva" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "mensagemBoasVindas" TEXT NOT NULL DEFAULT 'Olá, {nome_cliente}! Sua conta foi criada com sucesso.',
ADD COLUMN "mensagemPedidoConfirmadoAtiva" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "mensagemPedidoConfirmado" TEXT NOT NULL DEFAULT 'O pagamento do pedido {numero_pedido} foi confirmado.',
ADD COLUMN "mensagemPedidoEnviadoAtiva" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "mensagemPedidoEnviado" TEXT NOT NULL DEFAULT 'Seu pedido {numero_pedido} está a caminho!',
ADD COLUMN "mensagemPedidoEntregueAtiva" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "mensagemPedidoEntregue" TEXT NOT NULL DEFAULT 'Seu pedido {numero_pedido} foi entregue!',
ADD COLUMN "metaPixelAtivo" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "metaPixelId" TEXT,
ADD COLUMN "googleAnalyticsAtivo" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "googleAnalyticsId" TEXT,
ADD COLUMN "googleTagManagerAtivo" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "googleTagManagerId" TEXT,
ADD COLUMN "tiktokPixelAtivo" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "tiktokPixelId" TEXT,
ADD COLUMN "customHeadCodeAtivo" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "customHeadCode" TEXT,
ADD COLUMN "modoManutencao" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "mensagemManutencao" TEXT NOT NULL DEFAULT 'Estamos preparando novidades. Voltamos em breve!',
ADD COLUMN "valorMinimoPedido" DECIMAL(10,2) NOT NULL DEFAULT 0;

UPDATE "StoreSettings"
SET
  "instagramAtivo" = "linkInstagram" IS NOT NULL,
  "facebookAtivo" = "linkFacebook" IS NOT NULL,
  "tiktokAtivo" = "linkTiktok" IS NOT NULL,
  "shopeeAtivo" = "linkShopee" IS NOT NULL,
  "emailSuporteAtivo" = "emailSuporte" IS NOT NULL,
  "telefoneSuporteAtivo" = "telefoneSuporte" IS NOT NULL,
  "whatsappAtivo" = "whatsapp" IS NOT NULL;
