-- AlterTable
ALTER TABLE "ProductVariant" ADD COLUMN     "alturaCm" DOUBLE PRECISION NOT NULL DEFAULT 4,
ADD COLUMN     "comprimentoCm" DOUBLE PRECISION NOT NULL DEFAULT 11,
ADD COLUMN     "larguraCm" DOUBLE PRECISION NOT NULL DEFAULT 16,
ADD COLUMN     "pesoKg" DOUBLE PRECISION NOT NULL DEFAULT 0.3;

