"use client";

import { useState, useTransition } from "react";
import { CheckCircle2, Loader2, Save } from "lucide-react";
import { saveSettingsAction } from "@/lib/actions/settings";

type Initial = { nomeLoja: string; descricaoFooter: string; mensagemFooter: string; barraAnuncioAtiva: boolean; barraAnuncioTexto: string | null; barraAnuncioLink: string | null; emailSuporte: string | null; telefoneSuporte: string | null; whatsapp: string | null; linkShopee: string | null; linkInstagram: string | null; linkFacebook: string | null; linkTiktok: string | null };
const inputClass = "rounded-lg border border-white/10 bg-[#090909] px-3 py-2.5 text-sm text-white outline-none focus:border-[#A9EC17]/50";

export default function SettingsForm({ initial }: { initial: Initial }) {
  const [form, setForm] = useState({ ...initial, barraAnuncioTexto: initial.barraAnuncioTexto ?? "", barraAnuncioLink: initial.barraAnuncioLink ?? "", emailSuporte: initial.emailSuporte ?? "", telefoneSuporte: initial.telefoneSuporte ?? "", whatsapp: initial.whatsapp ?? "", linkShopee: initial.linkShopee ?? "", linkInstagram: initial.linkInstagram ?? "", linkFacebook: initial.linkFacebook ?? "", linkTiktok: initial.linkTiktok ?? "" });
  const [error, setError] = useState<string | null>(null); const [saved, setSaved] = useState(false); const [pending, startTransition] = useTransition();
  const set = (key: keyof typeof form, value: string | boolean) => setForm({ ...form, [key]: value });
  function submit(event: React.FormEvent) { event.preventDefault(); setError(null); setSaved(false); startTransition(async () => { const result = await saveSettingsAction(form); if (!result.ok) return setError(result.error); setSaved(true); }); }
  return <form onSubmit={submit} className="max-w-4xl space-y-5">
    <p className="text-sm text-white/50">Conteúdo institucional e canais exibidos na loja. Alterações entram no storefront sem novo deploy.</p>
    <section className="rounded-xl border border-white/[0.08] bg-[#111111] p-5"><h2 className="font-display font-bold">Identidade e rodapé</h2><div className="mt-4 grid gap-4 md:grid-cols-2"><label className="flex flex-col gap-1 text-xs text-white/60">Nome da loja<input required value={form.nomeLoja} onChange={(e) => set("nomeLoja", e.target.value)} className={inputClass} /></label><label className="flex flex-col gap-1 text-xs text-white/60">Mensagem curta do rodapé<input required value={form.mensagemFooter} onChange={(e) => set("mensagemFooter", e.target.value)} className={inputClass} /></label><label className="flex flex-col gap-1 text-xs text-white/60 md:col-span-2">Descrição institucional<textarea required value={form.descricaoFooter} onChange={(e) => set("descricaoFooter", e.target.value)} className={`${inputClass} min-h-20`} /></label></div></section>
    <section className="rounded-xl border border-white/[0.08] bg-[#111111] p-5"><div className="flex items-center justify-between"><div><h2 className="font-display font-bold">Barra de anúncio</h2><p className="mt-1 text-xs text-white/40">Aviso promocional no topo da loja.</p></div><label className="flex items-center gap-2 text-sm text-white/65"><input type="checkbox" checked={form.barraAnuncioAtiva} onChange={(e) => set("barraAnuncioAtiva", e.target.checked)} className="accent-[#A9EC17]" /> Ativa</label></div><div className="mt-4 grid gap-4 md:grid-cols-2"><label className="flex flex-col gap-1 text-xs text-white/60">Texto<input value={form.barraAnuncioTexto} onChange={(e) => set("barraAnuncioTexto", e.target.value)} className={inputClass} placeholder="Frete grátis acima de…" /></label><label className="flex flex-col gap-1 text-xs text-white/60">Link opcional<input type="url" value={form.barraAnuncioLink} onChange={(e) => set("barraAnuncioLink", e.target.value)} className={inputClass} placeholder="https://…" /></label></div></section>
    <section className="rounded-xl border border-white/[0.08] bg-[#111111] p-5"><h2 className="font-display font-bold">Atendimento</h2><div className="mt-4 grid gap-4 md:grid-cols-3"><label className="flex flex-col gap-1 text-xs text-white/60">E-mail<input type="email" value={form.emailSuporte} onChange={(e) => set("emailSuporte", e.target.value)} className={inputClass} /></label><label className="flex flex-col gap-1 text-xs text-white/60">Telefone<input value={form.telefoneSuporte} onChange={(e) => set("telefoneSuporte", e.target.value)} className={inputClass} /></label><label className="flex flex-col gap-1 text-xs text-white/60">WhatsApp<input value={form.whatsapp} onChange={(e) => set("whatsapp", e.target.value)} className={inputClass} /></label></div></section>
    <section className="rounded-xl border border-white/[0.08] bg-[#111111] p-5"><h2 className="font-display font-bold">Canais e redes sociais</h2><div className="mt-4 grid gap-4 md:grid-cols-2">{([['linkShopee','Shopee'],['linkInstagram','Instagram'],['linkFacebook','Facebook'],['linkTiktok','TikTok']] as const).map(([key, label]) => <label key={key} className="flex flex-col gap-1 text-xs text-white/60">{label}<input type="url" value={form[key]} onChange={(e) => set(key, e.target.value)} className={inputClass} placeholder="https://…" /></label>)}</div></section>
    {error ? <p className="rounded-lg border border-red-500/25 bg-red-500/10 px-3 py-2 text-sm text-red-300">{error}</p> : null}{saved ? <p className="flex items-center gap-2 rounded-lg border border-[#A9EC17]/20 bg-[#A9EC17]/5 px-3 py-2 text-sm text-[#A9EC17]"><CheckCircle2 className="h-4 w-4" /> Configurações salvas.</p> : null}<button disabled={pending} className="inline-flex items-center gap-2 rounded-lg bg-[#A9EC17] px-5 py-2.5 text-sm font-semibold text-black disabled:opacity-60">{pending ? <Loader2 className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />} Salvar configurações</button>
  </form>;
}
