/* eslint-disable @next/next/no-img-element */
"use client";

import { useState, useTransition } from "react";
import { ImageIcon, Loader2, Pencil, Plus, Trash2, X } from "lucide-react";
import { useRouter } from "next/navigation";
import BannerImageUploader from "@/components/banners/BannerImageUploader";
import { deleteBannerAction, saveBannerAction } from "@/lib/actions/banner";
import { bannerSpecs, type BannerPositionValue } from "@/lib/bannerSpecs";
import type { BannerListItem } from "@/lib/services/bannerAdminService";

type Draft = { id: string | null; nome: string; imagemUrl: string; altText: string; linkUrl: string; posicao: BannerPositionValue; largura: number; altura: number; ordem: string; ativo: boolean; inicioEm: string; expiraEm: string };
const blankDraft = (): Draft => ({ id: null, nome: "", imagemUrl: "", altText: "", linkUrl: "", posicao: "hero_slide", largura: 0, altura: 0, ordem: "0", ativo: true, inicioEm: "", expiraEm: "" });
const dateValue = (value: string | null) => value ? new Date(value).toISOString().slice(0, 16) : "";
const inputClass = "rounded-lg border border-white/10 bg-[#090909] px-3 py-2.5 text-sm text-white outline-none focus:border-[#A9EC17]/50";

export default function BannerManager({ banners }: { banners: BannerListItem[] }) {
  const router = useRouter(); const [draft, setDraft] = useState<Draft | null>(null); const [error, setError] = useState<string | null>(null); const [pending, startTransition] = useTransition();
  function edit(banner: BannerListItem) { setError(null); setDraft({ ...banner, linkUrl: banner.linkUrl ?? "", ordem: String(banner.ordem), inicioEm: dateValue(banner.inicioEm), expiraEm: dateValue(banner.expiraEm) }); }
  function submit(event: React.FormEvent) { event.preventDefault(); if (!draft) return; startTransition(async () => { const result = await saveBannerAction(draft.id, draft); if (!result.ok) return setError(result.error); setDraft(null); router.refresh(); }); }
  function remove(banner: BannerListItem) { if (!window.confirm(`Excluir o banner “${banner.nome}”?`)) return; startTransition(async () => { const result = await deleteBannerAction(banner.id); if (!result.ok) return setError(result.error); router.refresh(); }); }
  function position(value: BannerPositionValue) { if (!draft) return; setDraft({ ...draft, posicao: value, imagemUrl: "", largura: 0, altura: 0 }); }
  const spec = draft ? bannerSpecs[draft.posicao] : null;
  return <div className="space-y-4">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm text-white/50">{banners.length} banner(s) configurado(s).</p><p className="mt-1 text-xs text-white/30">A dimensão é validada antes do upload para preservar o layout da loja.</p></div><button onClick={() => { setDraft(blankDraft()); setError(null); }} className="inline-flex items-center gap-2 rounded-lg bg-[#A9EC17] px-4 py-2.5 text-sm font-semibold text-black"><Plus className="h-4 w-4" /> Novo banner</button></div>
    {draft && spec ? <form onSubmit={submit} className="rounded-xl border border-[#A9EC17]/20 bg-[#111111] p-5"><div className="mb-5 flex items-center justify-between"><div><h2 className="font-display font-bold">{draft.id ? "Editar banner" : "Novo banner"}</h2><p className="mt-1 text-xs text-white/40">{spec.description}</p></div><button type="button" onClick={() => setDraft(null)}><X className="h-5 w-5 text-white/40" /></button></div>
      <div className="grid gap-4 md:grid-cols-2"><label className="flex flex-col gap-1 text-xs text-white/60">Nome interno<input required value={draft.nome} onChange={(e) => setDraft({ ...draft, nome: e.target.value })} className={inputClass} /></label><label className="flex flex-col gap-1 text-xs text-white/60">Posição<select value={draft.posicao} onChange={(e) => position(e.target.value as BannerPositionValue)} className={inputClass}>{Object.entries(bannerSpecs).map(([value, item]) => <option key={value} value={value}>{item.label} — {item.width}×{item.height}px</option>)}</select></label><div className="md:col-span-2"><BannerImageUploader value={draft.imagemUrl} width={spec.width} height={spec.height} onChange={(image) => setDraft({ ...draft, imagemUrl: image.url, largura: image.width, altura: image.height })} /></div><label className="flex flex-col gap-1 text-xs text-white/60">Texto alternativo<input required value={draft.altText} onChange={(e) => setDraft({ ...draft, altText: e.target.value })} className={inputClass} placeholder="Descreva o conteúdo da imagem" /></label><label className="flex flex-col gap-1 text-xs text-white/60">Link ao clicar<input type="url" value={draft.linkUrl} onChange={(e) => setDraft({ ...draft, linkUrl: e.target.value })} className={inputClass} placeholder="https://… (opcional)" /></label><label className="flex flex-col gap-1 text-xs text-white/60">Ordem<input type="number" min="0" value={draft.ordem} onChange={(e) => setDraft({ ...draft, ordem: e.target.value })} className={inputClass} /></label><label className="flex items-center gap-2 self-end py-2 text-sm text-white/65"><input type="checkbox" checked={draft.ativo} onChange={(e) => setDraft({ ...draft, ativo: e.target.checked })} className="accent-[#A9EC17]" /> Banner ativo</label><label className="flex flex-col gap-1 text-xs text-white/60">Início<input type="datetime-local" value={draft.inicioEm} onChange={(e) => setDraft({ ...draft, inicioEm: e.target.value })} className={inputClass} /></label><label className="flex flex-col gap-1 text-xs text-white/60">Expiração<input type="datetime-local" value={draft.expiraEm} onChange={(e) => setDraft({ ...draft, expiraEm: e.target.value })} className={inputClass} /></label></div>
      {error ? <p className="mt-4 rounded-lg border border-red-500/25 bg-red-500/10 px-3 py-2 text-sm text-red-300">{error}</p> : null}<div className="mt-5 flex gap-3"><button disabled={pending || !draft.imagemUrl} className="inline-flex items-center gap-2 rounded-lg bg-[#A9EC17] px-4 py-2 text-sm font-semibold text-black disabled:opacity-50">{pending ? <Loader2 className="h-4 w-4 animate-spin" /> : null} Salvar</button><button type="button" onClick={() => setDraft(null)} className="rounded-lg border border-white/10 px-4 py-2 text-sm text-white/60">Cancelar</button></div></form> : error ? <p className="rounded-lg border border-red-500/25 bg-red-500/10 px-3 py-2 text-sm text-red-300">{error}</p> : null}
    {banners.length === 0 ? <div className="flex min-h-72 flex-col items-center justify-center rounded-xl border border-dashed border-white/10 bg-[#111111] text-center"><ImageIcon className="h-10 w-10 text-white/20" /><h2 className="font-display mt-4 font-bold">Nenhum banner cadastrado</h2><p className="mt-1 text-sm text-white/40">Escolha uma posição e envie uma imagem no tamanho exato.</p></div> : <div className="grid gap-4 lg:grid-cols-2">{banners.map((banner) => <article key={banner.id} className="overflow-hidden rounded-xl border border-white/[0.08] bg-[#111111]"><img src={banner.imagemUrl} alt={banner.altText} className="aspect-[3/1] w-full object-cover" /><div className="flex items-start justify-between gap-3 p-4"><div><p className="font-semibold text-white">{banner.nome}</p><p className="mt-1 text-xs text-white/40">{bannerSpecs[banner.posicao].label} · {banner.largura}×{banner.altura}px · ordem {banner.ordem}</p><span className={`mt-2 inline-flex rounded-full px-2 py-1 text-[10px] ${banner.ativo ? "bg-[#A9EC17]/10 text-[#A9EC17]" : "bg-white/5 text-white/35"}`}>{banner.ativo ? "Ativo" : "Inativo"}</span></div><div className="flex"><button onClick={() => edit(banner)} className="p-2 text-white/45 hover:text-white"><Pencil className="h-4 w-4" /></button><button onClick={() => remove(banner)} className="p-2 text-red-400/60 hover:text-red-300"><Trash2 className="h-4 w-4" /></button></div></div></article>)}</div>}
  </div>;
}
